### ISSUE TITLE
query conflicts with opaque

### ISSUE THREAD

**Issue by boris** [evenup/lita-sensu#7]
Can make it work with ruby 2.1.0 (using rbenv), getting weird error: `query conflicts with opaque`.

Here's the full backtrace:

```
[2015-10-07 14:27:33 UTC] INFO: Connected to Slack.
[2015-10-07 14:27:41 UTC] ERROR: Lita::Handlers::Sensu crashed. The exception was:
query conflicts with opaque
Full backtrace:
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/2.1.0/uri/generic.rb:890:in `check_query'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/2.1.0/uri/generic.rb:936:in `query='
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/connection.rb:407:in `build_exclusive_url'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:191:in `build_env'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/connection.rb:140:in `get'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lita-sensu-0.2.0/lib/lita/handlers/sensu.rb:34:in `http_get'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lita-sensu-0.2.0/lib/lita/handlers/sensu.rb:78:in `clients'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lita-4.6.1/lib/lita/callback.rb:31:in `public_send'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lita-4.6.1/lib/lita/callback.rb:31:in `call'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lita-4.6.1/lib/lita/handler/chat_router.rb:97:in `dispatch_to_route'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lita-4.6.1/lib/lita/handler/chat_router.rb:82:in `block in dispatch'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lita-4.6.1/lib/lita/handler/chat_router.rb:72:in `map'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lita-4.6.1/lib/lita/handler/chat_router.rb:72:in `dispatch'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lita-4.6.1/lib/lita/robot.rb:69:in `block in receive'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/2.1.0/set.rb:263:in `each_key'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/2.1.0/set.rb:263:in `each'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lita-4.6.1/lib/lita/robot.rb:66:in `map'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lita-4.6.1/lib/lita/robot.rb:66:in `receive'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lita-slack-1.7.0/lib/lita/adapters/slack/message_handler.rb:119:in `dispatch_message'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lita-slack-1.7.0/lib/lita/adapters/slack/message_handler.rb:159:in `handle_message'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lita-slack-1.7.0/lib/lita/adapters/slack/message_handler.rb:18:in `handle'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lita-slack-1.7.0/lib/lita/adapters/slack/rtm_connection.rb:100:in `block in receive_message'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/lita-slack-1.7.0/lib/lita/adapters/slack/event_loop.rb:10:in `block in defer'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:1062:in `call'
/home/deploy/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:1062:in `block in spawn_threadpool'
```

**Comment by boris** [comment]
solved the issue adding `https` on `lita_config.rb`
